### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Sh4d0wless** [develop54321/Gms#30]
hello...
i got error 500 after instalation

APACHE version = 2.4.54.2
PHP version = 7.4.33
MySQL version = 5.7.40

extension=bz2
extension=curl
extension=gd2
extension=mbstring

short_open_tag = On

PHP error

```
[22-Feb-2024 09:11:24 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function FastRoute\simpleDispatcher() in C:\wamp\www\core\Route.php:17
Stack trace:
#0 C:\wamp\www\index.php(29): core\Route->start()
#1 {main}
  thrown in C:\wamp\www\core\Route.php on line 17

```

**Comment by develop54321** [comment]
Look here please: https://github.com/develop54321/Gms/issues/29
